version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: NOM_BASE_DE_DONNNES
      POSTGRES_USER: UTILISATEUR_BDD
      POSTGRES_PASSWORD: MOT_DE_PASSE_BDD
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
